services:
  coolify-badge:
    build: .
    container_name: coolify-badge-service
    restart: always
    environment:
      - COOLIFY_URL=${COOLIFY_URL}
      - API_TOKEN=${API_TOKEN}
      - PORT=${PORT:-3000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coolify-badge.rule=Host(`${coolify.domain}`)"
      - "traefik.http.services.coolify-badge.loadbalancer.server.port=3000"
      - "traefik.http.services.coolify-badge.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.coolify-badge.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.coolify-badge.loadbalancer.healthcheck.timeout=2s"
    expose:
      - "3000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 32M
          cpus: "0.1"
